index markup
htmlacademy-adaptive/1853163-pink-25 pull request #2
Opened 2022-04-03 13:11 UTC by olgapecheniuk

2022-04-04 08:37 UTC, mikhin commented on source/index.html
> +<body class="page__body">
Для этого элемента где-то должен быть родительский блок

2022-04-04 08:37 UTC, mikhin commented on source/index.html
> +    <img class="logo-image" src="img/logo-mobile.svg" width="74" height="23" alt="Приложение Pink">
`logo` и `logo-image` это разные бэм-блоки по задумке?

2022-04-04 08:40 UTC, mikhin commented on source/index.html
> +        <a>
Есть очень хорошая практика — размечать классами вообще весь HTML, даже если классы будут не нужны при стилизации. Большая польза будет в том, что код HTML становится более читабельным и более понятным, например, для твоих коллег-разработчиков.

2022-04-04 08:41 UTC, mikhin commented on source/index.html
> +      <li class="site-list__item">
Кажется, тут опечатка — странное имя у элемента

2022-04-04 08:41 UTC, mikhin commented on source/index.html
> +    <ul class="main-nav__list">
опечатка в имени бэм-блока?

2022-04-04 08:41 UTC, mikhin commented on source/index.html
> +  <header class="main-header">
Вроде тут уже не хедер, а основный контент сайта пошел?

2022-04-04 08:42 UTC, mikhin commented on source/index.html
> +    <button class="main-container__button" type="button">Скачать приложение</button>
А вот этот элемент, он действительно контейнеру принадлежит или какому-то другому блоку, судя по дизайну?

Т.е. если мы перенесем контейнер на другую страницу, этот элемент тоже должен быть готов к переносу?

2022-04-04 08:43 UTC, mikhin commented on source/index.html
> +            <img src="img/apple.svg" class="operating-system__icon" alt="IOS" width="47" height="65">
alt'ы слабоваты =) по ним не поймешь что изображено на картинке

2022-04-04 08:43 UTC, mikhin commented on source/index.html
> +  <section class="advertising">
Section — это не замена div, это тег, имеющий свой семантический смысл. Section — это именно раздел контента, за которым пришел пользователь. Например, если на странице представлены рецепты для разных категорий, или представлены описания автозапчастей. Т.е. этот тег он именно отделяет независимые большие части контента друг от друга.

2022-04-04 08:44 UTC, mikhin commented on source/index.html
> +    <p class="advertising-slogan">Устали от серости мегаполиса?</p>
Вот этот абзац, это действительно независимый бэм-блок? Кажется, ему лучше быть частью (элементом) какого-то другого бэм-блока

2022-04-04 08:45 UTC, mikhin commented on source/index.html
> +      <div class="reviews__list slider__list">
Это не формальная ошибка по БЭМ, но это большое практическое неудобство — почти никогда мы не должны хотеть смешивать в разметке два разных БЭМ-блока, т.к. блоки — это уникальные сущности, они могут быть и должны использоваться независимо друг от друга.

Сейчас, по смешению блоков в этом участке кода я не могу представить себе, как мне отдельно использовать `reviews` и `slider`.

2022-04-04 08:45 UTC, mikhin commented on source/index.html
> +        <button class="slider__toggle" type="button">2</button>
хорошо, что указываешь тип кнопки, многие про это забывают

2022-04-04 08:46 UTC, mikhin commented on source/index.html
> +        <button class="slider__toggle slider__toggle--current" type="button">1</button>
правильно используются модификаторы — вместе с основным классом, круто!

2022-04-04 08:46 UTC, mikhin commented on source/index.html
> +        <th class="price-table__header"></th>
Зачем пустой элемент? По идее не должны хотеть такое

2022-04-04 08:47 UTC, mikhin commented on source/index.html
> +          <span class="rate-name">База</span>
Я бы не выделял тут сущности в отдельные бэм-блоки, т.к. они слишком мелки для этого

2022-04-04 08:48 UTC, mikhin commented on source/index.html
> +      <button class="slider__toggle slider__toggle--current" type="button">1</button>
Нельзя тут использовать элементы блока slider, если сам слайдер не используется тут и не является для них родителем.

2022-04-04 08:48 UTC, mikhin commented on source/index.html
> +        <a href="#" class="contacts__adress"> ул. Большая
address

2022-04-04 08:48 UTC, mikhin requested changes
нужно немного поправить

2022-04-05 07:31 UTC, olgapecheniuk commented on source/index.html
> +        <th class="price-table__header"></th>
я не очень понимаю, как сделать эту таблицу без пустого элемента в этом месте(

2022-04-05 17:21 UTC, merged