add styles
htmlacademy-adaptive/1853163-pink-25 pull request #4
Opened 2022-04-12 19:41 UTC by olgapecheniuk

2022-04-14 06:15 UTC, mikhin commented
@olgapecheniuk , обрати внимание, проверка линтера завершилась с ошибкой

2022-04-14 06:16 UTC, mikhin commented
`package-lock.json` не должен быть закоммичен просто так, если нет никаких изменений в `package.json`

2022-04-14 06:34 UTC, mikhin requested changes
Нужно внести исправления

2022-04-14 06:34 UTC, mikhin commented on source/catalog.html
> +    <img class="page-header__logo--image" src="img/logo-mobile.svg" width="74" height="23" alt="Приложение Pink">
Ошибка по БЭМ: тут ты пишешь, что это элемент лого с модификатором имейдж, но модификаторы нельзя писать без основного класса рядом, который ты модифицируешь. Получается должно быть `<img class="page-header__logo page-header__logo--image"`, но получается опять ошибка — такой элемент уже есть выше, ссылка, а в рамках блока разные по смыслу элементы не должны называться одинаково.

Если не очень понятен БЭМ, то предлагаю созвониться минут на 15 и обсудить)

2022-04-14 06:34 UTC, mikhin commented on source/catalog.html
> +      <li class="main-menu__item main-nav__item--active">
Очень частый кейс — как сверстать по БЭМ активную ссылку меню:

Сам `main-menu__item` скорее не должен хотеть отвечать за знание о том, активный он пункт или нет — этот айтем он скорее должен отвечать чисто за раскладку пунктов меню и их отношения между собой (отступы). Что находится внутри айтема ему должно быть все равно.

А вот как раз ссылка внутри и должна хотеть знать состояние — активная она или нет, дизейблед она или нет.

Но возникает противоречие вот где — если ссылка активная, она уже не должна быть по семантике ссылкой. Мы можем сделать ее спаном, и тогда наши стили очень хорошо лягут и на ссылку и на спан, т.к. они оба строчные элементы.

Но опять противоречие — если мы делаем активный пункт меню не ссылкой, а спаном, тогда мы не должны хотеть называть его `__link`, потому что получится несоответствие.

Выход такой — любой элемент внутри `__item` назвать `__item-content` и тогда у нас не будет противоречий с семантикой в разметке, и в этой же разметке мы сможем выставить любое нужное нам состояние и для ссылки и для спана.

2022-04-14 06:34 UTC, mikhin commented on source/form.html
> +      <label class="form__label form__label--achievement"><input type="checkbox" name="achievment"
Предлагаю не завязываться на контент в именовании

2022-04-14 06:34 UTC, mikhin commented on source/js/README
> +git pull academy master
Лишнее

2022-04-14 06:34 UTC, mikhin commented on source/less/advantage.less
> +  font-weight: 700;
Если по семантике это `h...`, то вроде у них дефолтное значение это?

2022-04-14 06:34 UTC, mikhin commented on source/less/advantage.less
> +.advantages__list {
Для `ul`, `ol`, еще полезно сбрасывать марджины и паддинги

2022-04-14 06:34 UTC, mikhin commented on source/less/advantage.less
> +  color: #283645;
А было уже в лекциях про то что цвета лучше выносить в переменные?

2022-04-14 06:34 UTC, mikhin commented on source/less/body.less
> +  min-height: 100%;
Не должны хотеть просто так такое

2022-04-14 06:34 UTC, mikhin commented on source/less/body.less
> +  margin: 0;
А было в лекциях про ресет и нормалайз?

2022-04-14 06:34 UTC, mikhin commented on source/less/body.less
> +  color: #000000;
Это вроде дефолт и так

2022-04-14 06:34 UTC, mikhin commented on source/less/download-container.less
> +  border-radius: 29px;
Лучше округлять до ровных значений: четных, кратных двух, пяти и т.д.

2022-04-14 06:34 UTC, mikhin commented on source/less/form.less
> +.form__legend--textarea {
Если эти все модификаторы имеют одинаковые стили, то может они и не нужны? Ну типа может сразу на элемент эти стили повесить и все, и разметка будет чище

2022-04-14 06:34 UTC, mikhin commented on source/less/form.less
> +.form__label--radio {
Если эти все модификаторы имеют одинаковые стили, то может они и не нужны? Ну типа может сразу на элемент эти стили повесить и все, и разметка будет чище

2022-04-14 06:34 UTC, mikhin commented on source/less/form.less
> +.form__fieldset--radio {
Если эти все модификаторы имеют одинаковые стили, то может они и не нужны? Ну типа может сразу на элемент эти стили повесить и все, и разметка будет чище

2022-04-14 06:34 UTC, mikhin commented on source/less/global.less
> +img {
По опыту рабочих проектов я бы не стал такое делать, — лучше определить локально где нужно. Глобальные стили очень легко писать и очень тяжело поддерживать.

2022-04-14 06:34 UTC, mikhin commented on source/less/header.less
> +  background: rgb(0, 0, 0,);
последняя запятая не нужна, если не задаем альфа-канал

2022-04-14 06:34 UTC, mikhin commented on source/less/main-container.less
> +
лишняя строка

2022-04-14 06:34 UTC, mikhin commented on source/less/main-container.less
> +
лишняя строка

2022-04-14 06:34 UTC, mikhin commented on source/less/main-footer.less
> +.main-footer {
блоки лучше писать в начале файла

2022-04-14 06:34 UTC, mikhin commented on source/less/user-review.less
> +  margin-bottom: 20px;
золотое важное правило — все стили "внешней геометрии" (марджины, позиционирование и т.д.) нельзя писать на бэм-блоках, только на бэм-элементах и их модификаторах.

мы проектируем бэм-блоки так, что они должны быть независимыми от окружения и должны уметь встраиваться в любое окружение, как деталь конструктора лего. Если мы пишем внешнюю геометрию на сам блок — мы ограничиваем его применение, а не должны хотеть.

Если блок таки нужно спозиционировать как-то на странице, к нему нужно примиксовать сущность бэм-элемента от другого бэм-блока и все стили внешней геометрии повесить уже на этот бэм-элемент.

Про внешнюю геометрию можно почитать тут — https://ru.bem.info/methodology/css/#%D0%92%D0%BD%D0%B5%D1%88%D0%BD%D1%8F%D1%8F-%D0%B3%D0%B5%D0%BE%D0%BC%D0%B5%D1%82%D1%80%D0%B8%D1%8F-%D0%B8-%D0%BF%D0%BE%D0%B7%D0%B8%D1%86%D0%B8%D0%BE%D0%BD%D0%B8%D1%80%D0%BE%D0%B2%D0%B0%D0%BD%D0%B8%D0%B5

2022-04-14 13:06 UTC, olgapecheniuk commented on source/less/advantage.less
> +  color: #283645;
Было о том, что так делать можно. А о том, что так делать лучше, не было вроде. Или я упустила этот момент

2022-04-14 13:06 UTC, olgapecheniuk commented on source/less/body.less
> +  margin: 0;
Было как-то в общих чертах

2022-04-15 10:00 UTC, mikhin commented on source/form.html
> +      <label class="form__label form__label--contacts">ИМЯ:<br>
@olgapecheniuk 

Тоже самое осталось =) Привязка нейминга к контенту. Суть в том, что контент тут может быть любой, не обязательно про контакты пользователя. Мы должны уметь взять эту же разметку и стили формы и сделать из нее форму "каких собак вы больше любите?", и вот уже `form__label--contacts` будет неуместным.

2022-04-15 10:00 UTC, merged